# Generated by Django 4.0.6 on 2023-02-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='calegory',
            new_name='category',
        ),
    ]
